# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Windows file lock mitigations to prevent "Couldn't delete R.jar / file in use by another process" errors
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
ksp.incremental=false


