package com.panda.keyboards.ime.keyboard

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

import androidx.compose.ui.text.font.FontFamily

/**
 * Live suggestion strip UI displayed above QWERTY keyboard rows.
 *
 * Renders up to 4 suggestion chips. Tapping a chip commits the full word
 * suggestion + trailing space to the active input field.
 *
 * When no suggestions or quick-paste clips are available, renders
 * "Panda Keyboards" as a centered branded placeholder text.
 *
 * @param suggestions List of candidate words generated by SuggestionEngine.
 * @param onSuggestionClick Callback when a suggestion chip is tapped.
 * @param resolvedTheme Theme color tokens.
 */
@Composable
fun SuggestionBar(
    suggestions: List<String>,
    onSuggestionClick: (String) -> Unit,
    resolvedTheme: ResolvedTheme,
    modifier: Modifier = Modifier,
    quickPasteText: String? = null,
    onQuickPasteClick: ((String) -> Unit)? = null
) {
    Surface(
        modifier = modifier
            .fillMaxWidth()
            .height(36.dp),
        color = Color.Transparent
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 6.dp, vertical = 2.dp),
            horizontalArrangement = Arrangement.spacedBy(6.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            if (suggestions.isNotEmpty()) {
                suggestions.take(4).forEach { suggestion ->
                    Surface(
                        modifier = Modifier
                            .weight(1f)
                            .height(32.dp)
                            .clip(RoundedCornerShape(10.dp))
                            .clickable { onSuggestionClick(suggestion) },
                        shape = RoundedCornerShape(10.dp),
                        color = resolvedTheme.specialKeyBackground.copy(alpha = 0.5f),
                        shadowElevation = 1.dp
                    ) {
                        Box(
                            modifier = Modifier.padding(horizontal = 6.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            Text(
                                text = suggestion,
                                color = resolvedTheme.keyText,
                                style = MaterialTheme.typography.bodyMedium,
                                fontFamily = FontFamily.Default,
                                fontWeight = FontWeight.SemiBold,
                                maxLines = 1,
                                overflow = TextOverflow.Ellipsis,
                                textAlign = TextAlign.Center,
                                fontSize = 13.sp
                            )
                        }
                    }
                }
            } else if (!quickPasteText.isNullOrBlank()) {
                // Quick-Paste Chip sharing ClipboardHistoryRepository state
                Surface(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(32.dp)
                        .clip(RoundedCornerShape(10.dp))
                        .clickable { onQuickPasteClick?.invoke(quickPasteText) },
                    shape = RoundedCornerShape(10.dp),
                    color = resolvedTheme.accent.copy(alpha = 0.25f),
                    shadowElevation = 1.dp
                ) {
                    Box(
                        modifier = Modifier.padding(horizontal = 12.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(
                            text = "📋 Paste \"${quickPasteText.replace("\n", " ").take(30)}\"",
                            color = resolvedTheme.keyText,
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Default,
                            fontWeight = FontWeight.SemiBold,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                            fontSize = 13.sp
                        )
                    }
                }
            } else {
                // Branded Placeholder Empty State
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(32.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        text = "Panda Keyboards",
                        color = resolvedTheme.keyText.copy(alpha = 0.45f),
                        style = MaterialTheme.typography.bodyMedium,
                        fontFamily = FontFamily.Default,
                        fontWeight = FontWeight.Medium,
                        fontSize = 13.sp,
                        textAlign = TextAlign.Center,
                        letterSpacing = 0.5.sp
                    )
                }
            }
        }
    }
}
